// DIMENSIONS  !important
#define SPHERE_RADIUS 0.5f
#define GAP_BETWEEN_PLATFORMS_SIZE 1
#define PLATFORM_WIDTH 2
#define PLATFORM_MAX_LENGTH 25
#define PLATFORM_LENGTH 15
#define PLATFORM_HEIGHT 0.05f
#define	init_window_width 2300
#define	init_window_height 1000
#define HALF_RECTANGLE_LENGTH 1

// POSITIONS
#define SPHERE_DEFAULT_HEIGHT SPHERE_RADIUS
#define PLAYER_MAX_LEFT -4.f
#define PLAYER_MAX_RIGHT 4.f

#define FUEL_BAR_X -0.985f
#define FUEL_BAR_Y 0.95f
#define FUEL_BAR_Z -1
#define FUEL_BAR_SCALE_X 70
#define FUEL_BAR_SCALE_Y 7



// INSTACE NUMBERS
#define MAX_PLATFORM_NUMBER 30
#define MAX_PLATFORM_COLUMNS 3


// PLATFORM TYPES
#define GREEN_PLATFORM 0
#define YELLOW_PLATFORM 1
#define ORANGE_PLATFORM 2
#define RED_PLATFORM 3
#define RED_PLATFORM_NAME "platformRed"
#define YELLOW_PLATFORM_NAME "platformYellow"
#define ORANGE_PLATFORM_NAME "platformOrange"
#define GREEN_PLATFORM_NAME "platformGreen"
#define PURPLE_PLATFORM_NAME "platformPurple"

// PLAYER Y AXE MOVEMENT TYPE
#define PLAYER_ON_THE_GROUND 0
#define PLAYER_IS_TAKING_OFF 1
#define PLAYER_IS_LANDING 2


// GAME PARAMETERS 
#define PLAYER_X_MOVE_STEP 0.1f
#define CAMERA_X_THIRD 0
#define CAMERA_Y_THIRD 2
#define CAMERA_Z_THIRD 4
#define CAMERA_X_FIRST 0
#define CAMERA_Y_FIRST 0.5f
#define CAMERA_Z_FIRST 0


#define PLAYER_MAX_SPEED 1.0f
#define PLAYER_DEFAULT_SPEED 0 /// TO DO 0.07f
#define PLAYER_SPEED_STEP 0.003f
#define PLAYER_MAX_HEIGHT 2.5f
#define PLAYER_JUMP_STEP 0.1f
#define PLAYER_MAX_FUEL 10.0f
#define PLAYER_FUEL_PENALTY 2.0f
#define PLAYER_FUEL_BONUS 7.0f;
#define PLAYER_FUEL_LOSS_STEP 0.01f
#define PLAYER_PENALTY_SPEED 0.2f
#define PLAYER_PENALTY_DURATION 2000
#define INTERVAL_BETWEEN_RED_PLATFORMS 2000
#define GAME_OVER_DEPTH -3
#define GAME_OVER_FALLING_STEP 0.05f
#define NOISE_ANIMATION_DURATION 300
