// DIMENSIONS  !important
#define SPHERE_RADIUS 0.5f
#define GAP_BETWEEN_PLATFORMS_SIZE 1
#define PLATFORM_WIDTH 2
#define PLATFORM_LENGTH 4.0f
#define PLATFORM_HEIGHT 0.1f
#define	init_window_width 2300
#define	init_window_height 1000

// POSITIONS
#define SPHERE_DEFAULT_HEIGHT SPHERE_RADIUS
#define PLAYER_MAX_LEFT -4.f
#define PLAYER_MAX_RIGHT 4.f


// INSTACE NUMBERS
#define MAX_PLATFORM_NUMBER 30
#define MAX_PLATFORM_COLUMNS 3


// PLATFORM TYPES
#define RED_PLATFORM 0
#define YELLOW_PLATFORM 1
#define ORANGE_PLATFORM 2
#define GREEN_PLATFORM 3
#define RED_PLATFORM_NAME "platformRed"
#define YELLOW_PLATFORM_NAME "platformYellow"
#define ORANGE_PLATFORM_NAME "platformOrange"
#define GREEN_PLATFORM_NAME "platformGreen"

// PLAYER Y AXE MOVEMENT TYPE
#define PLAYER_ON_THE_GROUND 0
#define PLAYER_IS_TAKING_OFF 1
#define PLAYER_IS_LANDING 2


// GAME PARAMETERS 
#define PLAYER_X_MOVE_STEP 0.05f
#define CAMERA_X_THIRD 0
#define CAMERA_Y_THIRD 2
#define CAMERA_Z_THIRD 4
#define CAMERA_X_FIRST 0
#define CAMERA_Y_FIRST 0.5f
#define CAMERA_Z_FIRST -1


#define PLAYER_DEFAULT_SPEED 0.3f
#define PLAYER_MAX_HEIGHT 2.5f
#define PLAYER_JUMP_STEP 0.1f

#define PLATFORM_Z_STEP 0.1f